# \n is a escape sequence character
information = 'hey i am sahil khola \n  i am a python developer \n  i love to code.'

# print(information)

# \t is a escape sequence character
information1 = 'hey i am sahil khola \t  i am a python developer \t  i love to code.'

# print(information1)

# \\ is a escape sequence character
information2 = 'hey i am sahil khola \\ i am a python developer \\  i love to code.'

# print(information2)

# \' is a escape sequence character
information3 = 'hey i am sahil khola \'i am a python developer\'  i love to code.'

print(information3)