# comment:>
#  single line comment
'''
#   multi line comment
    this is a comment
'''

# Escape Sequence Character:>
# \n: new line
# \t: tab
# \': single quote
# \": double quote
# \\: backslash
# print("Sahil khola , I am a \n programmer")
# print("Sahil khola , I am a \t programmer")
print("Sahil khola , I am a \' programmer \'")
# print("Sahil khola , I am a \" programmer \"")
# print("Sahil khola , I am a \\ programmer")

# print Statement:>
# print('Sahil khola',16,4,2004)
print('Sahil khola',16,4,2004, sep="~", end=" 009\n")
print(' Khola Rao shabh')

