# a = int(input('ENTER your Age : '))

# if elif else ladder

# if(a>=18):
#     print("You are adult")


# elif(a<0):
#     print("You enter invalid age")

# elif(a==0):
#     print("You enter Zero  age which is not valid age ")


# else:
#     print("You are children")    

# print("End of Program")    


# QUICK QUIZ
age  = int(input('ENTER your Age : '))

if(age>=18):
    print("Yess you above 18")

else:
    print("You are not greater than 18")    

