
# 7 + 4 = 11

# where 7 is the left operand and 4 is the right operand 
# and + is the operator and 11 is the result

#  Arthmetic Operators ------------------------------------->

# + Addition
# - Subtraction
# * Multiplication
# / Division

# a = 7
# b = 4

# c = a + b
# print(c)

# Assignment Operators ------------------------------------------>

# = Assignment
# += Add and assign
# -= Subtract and assign
# *= Multiply and assign
# /= Divide and assign

# a = 4-2 # Assign 4-2 to a

# b = 6

# b += 2 # Add 2 to b

# b -= 2 # Subtract 2 from b

# b *= 2 # Multiply b by 2

# b /= 2 # Divide b by 2


# print(a)
# print(b)


# Comparison Operators ---------------------------------------->

# == Equal to
# != Not equal to
# > Greater than
# < Less than
# >= Greater than or equal to
# <= Less than or equal to

# a = 4>3
# b = 4<3
# c = 4>=3
# d = 4<=3    
# e = 4!=3
# f = 4==4  



# print(a,b,c,d,e,f)

# Logical Operators ----------------------------------------->

# a = True or False
# b = True and False
# c = not True

# print(a,b,c)


# OR
# print('True or False =',True or False)
# print('True or true =',True or True)
# print('False or true =',False or True)
# print('False or false =',False or False)


# # AND
print('True and False =',True and False)
print('True and true =',True and True)
print('False and true =',False and True)
print('False and false =',False and False)


# NOT
# print('not True =',not True)
# print('not False =',not False)