d ={}

name = input("Enter Friends Name : ")
lang = input("Enter language name : ")
d.update({name:lang})

name = input("Enter Friends Name : ")
lang = input("Enter language name : ")
d.update({name:lang})

name = input("Enter Friends Name : ")
lang = input("Enter language name : ")
d.update({name:lang})

name = input("Enter Friends Name : ")
lang = input("Enter language name : ")
d.update({name:lang})

print(d)