print('Sahil Khola')
# What is Python?
# Ans : Python is a programming language that can be used to create programs that can be run on a computer. Python is a programming language that is used for creating websites and software.

# Why use Python?
# Ans : Python is a programming language that is easy to learn and use. Python is a programming language that is used for creating websites and software.

# What are the benefits of using Python?
# Ans : Python is a programming language that is easy to learn and use. Python is a programming language that is used for creating websites and software.

# Feature of Python?
# 1 Python is simple and easy to understand.
# 2 it is Interpreted and platform independent which make debugging easy.
# 3 it is free and open source.
# 4 it is dynamic and can be used for both small and large scale projects.

